server:
  port: ${PORT:8080}

spring:
  application:
    name: hotel-reservation
  datasource:
    url: jdbc:h2:file:/tmp/data/H2/db
    username: sa
    password: 
  h2:
    console:
        enabled: true
  sql:
      init:
          mode: always